libclang: Evaluate the options before starting a new thread
This fixes an error that arise because vim variables are not yet available
in the thread's context. This was the original error message:

Error detected while processing function <SNR>50_Detect:
E121: Undefined variable: b:clang_user_options
E15: Invalid expression: b:clang_user_options
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "SOMEPATHHERE/plugin/libclang.py", line 223, in run
    getCurrentTranslationUnit()
  File "SOMEPATHHERE/plugin/libclang.py", line 23, in
getCurrentTranslationUnit
    userOptionsLocal = splitOptions(vim.eval("b:clang_user_options"))
vim.error: invalid expression

Signed-off-by: Tobias Grosser <tobias@grosser.es>